export const exampleScenarios = [
  {
    key: 'llm-small',
    name: 'LLM Chatbot - small model',
    description: 'Shows token-driven inference behavior.',
    observe: 'Look for steady GPU compute with low queue wait and stable p99.',
    scenario: {
      name: 'LLM Chatbot - small model',
      analysis: { target_p99_ms: 180 },
      workload: { name: 'llm-chat-small', rps: 2, duration_s: 20, batch_size: 1, jitter_pct: 4 },
      target: {
        name: 'A10G',
        tflops: 60,
        mem_gbps: 600,
        ms_per_token: 0.16,
        h2d_gbps: 32,
        d2h_gbps: 32,
        concurrency: 2,
      },
      pipeline: [
        { name: 'preprocess', kind: 'fixed_ms', value: 2 },
        { name: 'h2d', kind: 'bytes', value: 6 * 1024 * 1024 },
        { name: 'compute', kind: 'tokens', value: 96 },
        { name: 'd2h', kind: 'bytes', value: 1 * 1024 * 1024 },
        { name: 'postprocess', kind: 'fixed_ms', value: 1.5 },
      ],
    },
  },
  {
    key: 'llm-traffic',
    name: 'LLM Chatbot - high traffic',
    description: 'Shows queueing and p99 growth.',
    observe: 'Watch queue share rise and compare Decision Summary against the timeline.',
    scenario: {
      name: 'LLM Chatbot - high traffic',
      analysis: { target_p99_ms: 240 },
      workload: { name: 'llm-chat-bursty', rps: 10, duration_s: 20, batch_size: 1, jitter_pct: 10 },
      target: {
        name: 'A10G',
        tflops: 60,
        mem_gbps: 600,
        ms_per_token: 0.2,
        h2d_gbps: 32,
        d2h_gbps: 32,
        concurrency: 2,
      },
      pipeline: [
        { name: 'preprocess', kind: 'fixed_ms', value: 2 },
        { name: 'h2d', kind: 'bytes', value: 8 * 1024 * 1024 },
        { name: 'compute', kind: 'tokens', value: 192 },
        { name: 'd2h', kind: 'bytes', value: 2 * 1024 * 1024 },
        { name: 'postprocess', kind: 'fixed_ms', value: 1.5 },
      ],
    },
  },
  {
    key: 'transfer-heavy',
    name: 'Transfer-heavy workload',
    description: 'Shows H2D/D2H bottlenecks.',
    observe: 'Inspect transfer lanes and compare transfer time against compute time.',
    scenario: {
      name: 'Transfer-heavy workload',
      analysis: { target_p99_ms: 160 },
      workload: { name: 'transfer-heavy', rps: 3, duration_s: 16, batch_size: 1, jitter_pct: 5 },
      target: {
        name: 'L4',
        tflops: 30,
        mem_gbps: 300,
        ms_per_token: 0.12,
        h2d_gbps: 20,
        d2h_gbps: 20,
        concurrency: 2,
      },
      pipeline: [
        { name: 'preprocess', kind: 'fixed_ms', value: 2 },
        { name: 'h2d', kind: 'bytes', value: 96 * 1024 * 1024 },
        { name: 'compute', kind: 'tokens', value: 24 },
        { name: 'd2h', kind: 'bytes', value: 48 * 1024 * 1024 },
        { name: 'postprocess', kind: 'fixed_ms', value: 1 },
      ],
    },
  },
  {
    key: 'gpu-bound',
    name: 'GPU-bound workload',
    description: 'Shows compute saturation.',
    observe: 'Look for high GPU busy percentage and limited headroom in Decision Summary.',
    scenario: {
      name: 'GPU-bound workload',
      analysis: { target_p99_ms: 300 },
      workload: { name: 'gpu-bound', rps: 4, duration_s: 18, batch_size: 1, jitter_pct: 4 },
      target: {
        name: 'A10G',
        tflops: 60,
        mem_gbps: 600,
        ms_per_token: 0.22,
        h2d_gbps: 32,
        d2h_gbps: 32,
        concurrency: 2,
      },
      pipeline: [
        { name: 'preprocess', kind: 'fixed_ms', value: 1.5 },
        { name: 'h2d', kind: 'bytes', value: 4 * 1024 * 1024 },
        { name: 'compute', kind: 'tokens', value: 320 },
        { name: 'd2h', kind: 'bytes', value: 1 * 1024 * 1024 },
        { name: 'postprocess', kind: 'fixed_ms', value: 1 },
      ],
    },
  },
  {
    key: 'balanced',
    name: 'Balanced workload',
    description: 'Shows healthy utilization.',
    observe: 'Use this as a baseline before comparing GPUs or running sweeps.',
    scenario: {
      name: 'Balanced workload',
      analysis: { target_p99_ms: 140 },
      workload: { name: 'balanced', rps: 3, duration_s: 18, batch_size: 1, jitter_pct: 3 },
      target: {
        name: 'A100',
        tflops: 155,
        mem_gbps: 1555,
        ms_per_token: 0.1,
        h2d_gbps: 80,
        d2h_gbps: 80,
        concurrency: 4,
      },
      pipeline: [
        { name: 'preprocess', kind: 'fixed_ms', value: 2 },
        { name: 'h2d', kind: 'bytes', value: 10 * 1024 * 1024 },
        { name: 'compute', kind: 'tokens', value: 96 },
        { name: 'd2h', kind: 'bytes', value: 4 * 1024 * 1024 },
        { name: 'postprocess', kind: 'fixed_ms', value: 2 },
      ],
    },
  },
]
